### ISSUE TITLE
Feature-Request: Knockback and Kick on low Distance

### ISSUE THREAD

**Issue by wolfkarst** [NotJansel/NotJanselLive#1]
If a Live-Player gets closer as 128 Blocks next to an offline-Player, he will get knocked away from from Offline-Player.
If a Live-Player gets closer as 64 Blocks next to an offline-Player, he will get kicked.
This will make special events like "Hunt the Streamer" possible.

**Comment by Paulaufyt** [comment]
Not gonna happen i think

**Comment by NotJansel** [comment]
sorry, but this is kinda too much, since it is also gonna be put on other servers... I would then rather do a server specific option to hide the player on the dynmap if the server has one.

**Comment by Paulaufyt** [comment]
that would mean streamsniping which is a d*ck move
